PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

INSERT INTO setting VALUES(1,'site','{"sitename":"M Blog","footertitle":"少年游","footercontent":"林花谢了春红 太匆匆 ","footercorp":"© 2016 Suntao Copyright -1","headclr":"blue","footclr":"blue"}');

INSERT INTO articles VALUES(2,'第二篇文章','第二篇文章依旧是一篇测试文',2,1464588802347,1464588802346);

INSERT INTO api VALUES(2,'overview','/admin/overview','overview访问权下');
INSERT INTO api VALUES(3,'custume','/admin/custume','个性化访问权限');
INSERT INTO api VALUES(4,'addblog','/articles/addblog','添加一个博客');
INSERT INTO api VALUES(5,'editblog','/articles/editblog','修改一个博客');
INSERT INTO api VALUES(6,'deleteblog','/articles/deleteblog','删除一个博客');
INSERT INTO api VALUES(7,'addcmt','/articles/comment/add','添加一个评论');
INSERT INTO api VALUES(8,'updatecmt','/articles/comment/update','修改一个评论');
INSERT INTO api VALUES(9,'deletecmt','/articles/comment/delete','删除一条评论');
INSERT INTO api VALUES(10,'adduser','/admin/users/add',NULL);
INSERT INTO api VALUES(11,'deleteuser','/admin/users/delete',NULL);
INSERT INTO api VALUES(12,'getuser','/admin/users/get',NULL);
INSERT INTO api VALUES(13,'updateuser','/admin/users/update',NULL);
INSERT INTO api VALUES(14,'login','/login',NULL);
INSERT INTO api VALUES(15,'register','/register',NULL);
INSERT INTO api VALUES(16,'logout','/logout',NULL);
INSERT INTO api VALUES(17,'usertypeadd','/admin/auth/usertype/add',NULL);
INSERT INTO api VALUES(18,'usertypeupdate','/admin/auth/usertype/update',NULL);
INSERT INTO api VALUES(19,'usertypapienable','/admin/auth/usertypeapi/enable',NULL);
INSERT INTO api VALUES(20,'usertypeapidisable','/admin/auth/usertypeapi/disable',NULL);
INSERT INTO api VALUES(21,'usertypeviewenable','/admin/auth/usertypeview/enable',NULL);
INSERT INTO api VALUES(22,'usertypeviewdisable','/admin/auth/usertypeview/disable',NULL);
INSERT INTO api VALUES(23,'costome','/admin/costume',NULL);
INSERT INTO api VALUES(24,'usertypedelete','/admin/auth/usertype/delete',NULL);

INSERT INTO usertype VALUES(0,'未登录','尚未登录');
INSERT INTO usertype VALUES(1,'管理员','管理员账户');
INSERT INTO usertype VALUES(2,'普通用户','普通的博客用户');

INSERT INTO "view" VALUES(1,'newblog','/articles/newblog','添加博客 页面');
INSERT INTO "view" VALUES(2,'editblog','/articles/editblog','修改博客页面');
INSERT INTO "view" VALUES(3,'blogmanager','/articles/blogmanager','博客管理器');
INSERT INTO "view" VALUES(4,'commentmanager','/articles/comment/commentmanager',NULL);
INSERT INTO "view" VALUES(5,'allblogs','/articles/allblogs','博客列表');
INSERT INTO "view" VALUES(6,'blog','/articles/blog','单独博客');
INSERT INTO "view" VALUES(7,'register','/register','注册页面');
INSERT INTO "view" VALUES(8,'usermanager','/admin/users/usermanager',NULL);
INSERT INTO "view" VALUES(9,'adduser','/admin/users/add',NULL);
INSERT INTO "view" VALUES(10,'updateuser','/admin/users/update',NULL);
INSERT INTO "view" VALUES(11,'overview','/admin/overview',NULL);
INSERT INTO "view" VALUES(12,'costume','/admin/costume',NULL);
INSERT INTO "view" VALUES(13,'index','/index',NULL);
INSERT INTO "view" VALUES(14,'login','/login',NULL);
INSERT INTO "view" VALUES(15,'usertypemanager','/admin/auth/usertype/manager','用户类型管理');
INSERT INTO "view" VALUES(16,'usertypeapimanager','/admin/auth/usertypeapi/manager','用户权限管理');
INSERT INTO "view" VALUES(17,'usertypeviewmanager','/admin/auth/usertypeview/manager',NULL);
INSERT INTO "view" VALUES(18,'usertypeadd','/admin/auth/usertype/add',NULL);
INSERT INTO "view" VALUES(19,'userytpeupdate','/admin/auth/usertype/update',NULL);

INSERT INTO usertypeview VALUES(1,1,1);
INSERT INTO usertypeview VALUES(2,1,2);
INSERT INTO usertypeview VALUES(3,1,3);
INSERT INTO usertypeview VALUES(4,1,4);
INSERT INTO usertypeview VALUES(5,1,5);
INSERT INTO usertypeview VALUES(6,1,6);
INSERT INTO usertypeview VALUES(7,1,7);
INSERT INTO usertypeview VALUES(8,1,8);
INSERT INTO usertypeview VALUES(9,1,9);
INSERT INTO usertypeview VALUES(10,1,10);
INSERT INTO usertypeview VALUES(11,1,11);
INSERT INTO usertypeview VALUES(12,1,12);
INSERT INTO usertypeview VALUES(13,1,13);
INSERT INTO usertypeview VALUES(14,0,13);
INSERT INTO usertypeview VALUES(15,1,14);
INSERT INTO usertypeview VALUES(16,0,14);
INSERT INTO usertypeview VALUES(17,0,5);
INSERT INTO usertypeview VALUES(18,0,6);
INSERT INTO usertypeview VALUES(19,2,14);
INSERT INTO usertypeview VALUES(20,2,13);
INSERT INTO usertypeview VALUES(21,1,15);
INSERT INTO usertypeview VALUES(22,1,16);
INSERT INTO usertypeview VALUES(23,1,17);
INSERT INTO usertypeview VALUES(24,1,18);
INSERT INTO usertypeview VALUES(25,1,19);
INSERT INTO usertypeview VALUES(30,3,7);
INSERT INTO usertypeview VALUES(31,0,7);
INSERT INTO usertypeview VALUES(32,2,1);
INSERT INTO usertypeview VALUES(33,2,2);
INSERT INTO usertypeview VALUES(35,2,11);
INSERT INTO usertypeview VALUES(36,2,10);
INSERT INTO usertypeview VALUES(37,2,6);
INSERT INTO usertypeview VALUES(38,2,5);

INSERT INTO usertypeapi VALUES(2,1,2);
INSERT INTO usertypeapi VALUES(3,1,3);
INSERT INTO usertypeapi VALUES(4,1,4);
INSERT INTO usertypeapi VALUES(5,1,5);
INSERT INTO usertypeapi VALUES(6,1,6);
INSERT INTO usertypeapi VALUES(7,1,7);
INSERT INTO usertypeapi VALUES(8,1,8);
INSERT INTO usertypeapi VALUES(9,1,9);
INSERT INTO usertypeapi VALUES(10,1,10);
INSERT INTO usertypeapi VALUES(11,1,11);
INSERT INTO usertypeapi VALUES(12,1,12);
INSERT INTO usertypeapi VALUES(13,1,13);
INSERT INTO usertypeapi VALUES(14,1,14);
INSERT INTO usertypeapi VALUES(15,1,15);
INSERT INTO usertypeapi VALUES(16,0,14);
INSERT INTO usertypeapi VALUES(17,1,16);
INSERT INTO usertypeapi VALUES(18,2,4);
INSERT INTO usertypeapi VALUES(19,2,5);
INSERT INTO usertypeapi VALUES(20,2,6);
INSERT INTO usertypeapi VALUES(21,1,17);
INSERT INTO usertypeapi VALUES(22,1,18);
INSERT INTO usertypeapi VALUES(23,1,19);
INSERT INTO usertypeapi VALUES(24,1,20);
INSERT INTO usertypeapi VALUES(38,1,21);
INSERT INTO usertypeapi VALUES(39,1,22);
INSERT INTO usertypeapi VALUES(42,2,7);
INSERT INTO usertypeapi VALUES(47,2,2);
INSERT INTO usertypeapi VALUES(49,1,23);
INSERT INTO usertypeapi VALUES(50,1,24);
INSERT INTO usertypeapi VALUES(56,2,16);
INSERT INTO usertypeapi VALUES(57,0,15);
INSERT INTO usertypeapi VALUES(58,2,9);
INSERT INTO usertypeapi VALUES(59,2,8);

INSERT INTO sqlite_sequence VALUES('comment',28);
INSERT INTO sqlite_sequence VALUES('api',24);
INSERT INTO sqlite_sequence VALUES('usertype',4);
INSERT INTO sqlite_sequence VALUES('usertypeview',39);
INSERT INTO sqlite_sequence VALUES('view',19);
INSERT INTO sqlite_sequence VALUES('usertypeapi',60);

COMMIT;
